export const PO_BASE_URL = "/material-po";
export const PO_PIPING_BASE_URL = "/piping/material-po";

const PO_ROUTE_URLS = {
    HOME: `${PO_BASE_URL}/dashboard`,
    LOGIN: `${PO_BASE_URL}/login`,
    SECTION_DETAILS: `${PO_BASE_URL}/section-details`,
    MANAGE_SECTION_DETAILS: `${PO_BASE_URL}/manage-section-details`,
    AREA_MASTER: `${PO_BASE_URL}/area-master`,
    MTO: `${PO_BASE_URL}/mto-management`,
    MANAGE_MTO: `${PO_BASE_URL}/manage-mto`,
    MTO_VIEW: `${PO_BASE_URL}/material-mto/mto-view`,
    PR: `${PO_BASE_URL}/pr-management`,
    PR_VIEW:`${PO_BASE_URL}/pr-view`,
    MANAGE_PR: `${PO_BASE_URL}/manage-pr`,
    INQUIRY: `${PO_BASE_URL}/inquiry-management`,
    MANAGE_INQUIRY: `${PO_BASE_URL}/manage-inquiry`,
    VIEW_INQUIRY: `${PO_BASE_URL}/view-inquiry`,
    OFF_COM: `${PO_BASE_URL}/offer-comparision-management`,
    CONTER_OFF: `${PO_BASE_URL}/counter-offer-management`,
    ORDER_PLACE: `${PO_BASE_URL}/order-management`,
    MANAGE_ORDER: `${PO_BASE_URL}/manage-order`,
    VIEW_ORDER: `${PO_BASE_URL}/view-order`,
    MATERIAL_CHART: `${PO_BASE_URL}/material-chart`,
    TERMS_AND_CONDITIONS: `${PO_BASE_URL}/terms-and-conditions`,
    MANAGE_TERMS_AND_CONDITIONS: `${PO_BASE_URL}/manage-terms-and-conditions`,
    MANAGE_MANUFACTURER: `${PO_BASE_URL}/manage-manufacturer`,
    MANUFACTURE_LIST: `${PO_BASE_URL}/manufacturer-list`,
    PIPING_HOME: `${PO_PIPING_BASE_URL}/dashboard`,
    PIPING_SECTION_DETAILS: `${PO_PIPING_BASE_URL}/section-details`,
    PIPING_MANAGE_SECTION_DETAILS: `${PO_PIPING_BASE_URL}/manage-section-details`,
    PIPING_AREA_MASTER: `${PO_PIPING_BASE_URL}/area-master`,
    PIPING_MTO: `${PO_PIPING_BASE_URL}/mto-management`,
    PIPING_MANAGE_MTO: `${PO_PIPING_BASE_URL}/manage-mto`,
    PIPING_MTO_VIEW: `${PO_PIPING_BASE_URL}/material-mto/mto-view`,
    PIPING_PR: `${PO_PIPING_BASE_URL}/pr-management`,
    PIPING_PR_VIEW:`${PO_PIPING_BASE_URL}/pr-view`,
    PIPING_MANAGE_PR: `${PO_PIPING_BASE_URL}/manage-pr`,
    PIPING_INQUIRY: `${PO_PIPING_BASE_URL}/inquiry-management`,
    PIPING_MANAGE_INQUIRY: `${PO_PIPING_BASE_URL}/manage-inquiry`,
    PIPING_VIEW_INQUIRY: `${PO_PIPING_BASE_URL}/view-inquiry`,
    PIPING_OFF_COM: `${PO_PIPING_BASE_URL}/offer-comparision-management`,
    PIPING_CONTER_OFF: `${PO_PIPING_BASE_URL}/counter-offer-management`,
    PIPING_ORDER_PLACE: `${PO_PIPING_BASE_URL}/order-management`,
    PIPING_MANAGE_ORDER: `${PO_PIPING_BASE_URL}/manage-order`,
    PIPING_VIEW_ORDER: `${PO_PIPING_BASE_URL}/view-order`,
    PIPING_MATERIAL_CHART: `${PO_PIPING_BASE_URL}/material-chart`,
    PIPING_TERMS_AND_CONDITIONS: `${PO_PIPING_BASE_URL}/terms-and-conditions`,
    PIPING_MANAGE_TERMS_AND_CONDITIONS: `${PO_PIPING_BASE_URL}/manage-terms-and-conditions`,
    PIPING_MANAGE_MANUFACTURER: `${PO_PIPING_BASE_URL}/manage-manufacturer`,
    PIPING_MANUFACTURE_LIST: `${PO_PIPING_BASE_URL}/manufacturer-list`
    
}

export default PO_ROUTE_URLS;